COHERE_API_KEY  = "j9zQPHBqHw6m5vGyA5OdKYC1PxCrJrmbEA4SzPtN"
SMTP_SERVER     = "smtp.gmail.com"
SMTP_PORT       = 587
SENDER_EMAIL    = "muthianibilly@gmail.com"
SENDER_PASSWORD = "dqfz trvv wgkb meoj"
